---
include:
  # - board:  nice_nano_v2
  #   shield: nine_left
  # - board:  nice_nano_v2
  #  shield: nine_right
  - board:  seeeduino_xiao_ble
    shield: anisote
  # - board: nice_nano_v2
  #   shield: cradio_left
  # - board: nice_nano_v2
  #   shield: cradio_right
  # - board: nice_nano_v2
  #   shield: reviung41
  # - board: sparkfun_pro_micro_rp2040
  #   shield: reviung41
  # - board: nice_nano_v2
  #   shield: corne_left
  # - board: nice_nano_v2
  #   shield: corne_right
  # - board: nice_nano_v2
  #   shield: settings_reset
